- name: Create a {{item.dir}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item.dir}}"
    url: http://172.31.0.48:8080
    user: admin
    password: "{{jenkins_password}}"
  loop:
    - "{{ folders}}"

- name: create jenkins jobs
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{ pipeline_jobs }}"