- name: copy config file
  ansible.builtin.template:
    src: jobs.xml
    dest: /tmp/mbranch.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)

- name: Create a {{item.dir}}/{{item.name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mbranch.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.0.48:8080
    user: admin
    password: "{{jenkins_password}}"