- name: check if job exists or not
  ansible.builtin.shell: java -jar jenkins-cli.jar -auth admin:{{jenkins_password}} -s http://172.31.0.48:8080/ -webSocket get-job {{item.dir}}/{{item.name}}
  register: out
  ignore_errors: yes

- name: copy config file
  ansible.builtin.template:
    src: mbranch.xml
    dest: /tmp/mbranch.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)
  when: out.rc ==3

- name: Create a {{item.dir}}/{{item.name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/mbranch.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.0.48:8080
    user: admin
    password: "{{jenkins_password}}"
  when: out.rc ==3