- name: check if job exists or not
  community.general.jenkins_job_info:
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.0.48:8080
    user: admin
    password: "{{jenkins_password}}"
  register: out
  ignore_errors: yes

- name: copy config file
  ansible.builtin.template:
    src: jobs.xml
    dest: /tmp/jobs.xml
  when: out.failed | bool

- name: Create a {{item.dir}}/{{item.name}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/jobs.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.0.48:8080
    user: admin
    password: "{{jenkins_password}}"
  when: out.failed | bool