- name: check if job exists or not
  ansible.builtin.shell: java -jar jenkins-cli.jar -auth admin:{{jenkins_password}} -s http://172.31.0.48:8080/ -webSocket get-job {{item.dir}}/{{item.name}}
  register: out
  ignore_errors: yes

- name: copy config file
  ansible.builtin.template:
    src: jobs.xml
    dest: /tmp/jobs.xml
  when: out.rc ==3

- name: Create a {{item.dir}}/{{item.name}} job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/jobs.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.0.48:8080
    user: admin
    password: "{{jenkins_password}}"
  when: out.rc ==3